### ISSUE TITLE
transform 模糊问题

### ISSUE THREAD

**Issue by mistory** [mistory/blog#3]
对于宽、高度不确定的元素来说，使用transform可以很方便的使元素居中，但最近在移动端页面中，使用transform后，元素内的文字模糊了

![transform](http://7xswki.com2.z0.glb.clouddn.com/mo.png)

网上翻了一下，也没有找到相关的解决办法，那就只能通过实践来处理了。

#### 1.padding/margin
原来的css是这样的
``` css
	.msg {
	    position: fixed;
	    left: 50%;
	    top: 50%;
	    background: #fff;
	    z-index: 9999;
	    transform: translate(-50%,-50%);
	    padding: .5rem;
	}
```
把 padding: .5rem 去掉后，文字就不再模糊了
![transform](http://7xswki.com2.z0.glb.clouddn.com/01.png)

于是又尝试了下em、px、pt以及百分比后，发现无论哪种单位，在某些取值下，都会造成模糊，margin也是一样。

#### 2.width/height
元素自身如果设置了width/height的话，同样会出现模糊的状况，不过如果宽高值固定的话，使用margin就能替代了

#### 3.overflow: hidden
``` css
	body { 
	    overflow: hidden;
	}
```
当页面没有滚动条时，transform的元素无论怎样定义css，都不会产生模糊的情况，于是，试着隐藏了滚动条，意外的管用！

ps：只适用于position为fixed/absolute的层。

![transform](http://7xswki.com2.z0.glb.clouddn.com/d.png)
