### ISSUE TITLE
使用padding解决手机端图片占位问题

### ISSUE THREAD

**Issue by mistory** [mistory/blog#6]
由于图片的加载是在dom加载完成之后进行的，于是，在手机端浏览网页时，经常会看到页面刚打开时很多内容叠在一起，当图片加载完成后，页面抖动以下才显示正常。（PC端也有这种问题，但手机端屏幕小，网速慢，问题比较突出，对用户体验不友好）

![图片高度问题](http://7xswki.com2.z0.glb.clouddn.com/22.gif)

而移动端不同设备的宽度不同，给图片设置固定px高度显然不能解决这个问题。

但是padding是可以百分比取值的（margin类同），详见[padding-properties](https://www.w3.org/TR/CSS2/box.html#padding-properties)

> The percentage is calculated with respect to the width of the generated box's containing block, even for 'padding-top' and 'padding-bottom'. If the containing block's width depends on this element, then the resulting layout is undefined in CSS 2.1.

即取值为百分比时，计算出来的padding边距相对于其父元素的宽度，如下图：

![padding](http://7xswki.com2.z0.glb.clouddn.com/padding.png)

那么，解决图片占位的问题就很简单了。
页面布局如下：

```html
<style>
    * {
        margin: 0;
        padding: 0;
    }
    ul {
        overflow: hidden;
    }
    li {
        width: 50%;
        float: left;
        text-align: center;
    }
    img {
        width: 100%
    }
</style>
<ul>
    <li>
        <div class="cover">
            <img src="2222.png" alt="">
        </div>
        <div>
            文字
        </div>
    </li>
</ul>
```

这里使用伪元素替代div充当子元素，由于padding-top使图片距离cover顶部100%，用相对定位到顶端。

```css
.cover {
    position: relative;
    font-size: 0;
    display: inline-block;
    width: 100%
}
.cover img {
    width: 100%;
    height: 100%;
    position: absolute;
    left: 0;
    top: 0;
}
.cover:after {
    content: '\20';
    padding-top: 100%;
    display: block;
}
```

页面最终效果如下：

![padding](http://7xswki.com2.z0.glb.clouddn.com/21.gif)

上述例子只适用于图片宽高1:1的情况，对于其他比例的图片需要修改**padding-top值**，例如宽高2:1的图片，padding-top改为50%即可。

当然也可以使用rem，但是需要手动对图片设置高度，如果页面布局发生了变化，例如两列变三列，又需要重新修改图片大小，比较麻烦，不过具体使用rem还是padding需要看需求而定。
